version: "3"
containers:
- name: host01
  image: ubuntu:22.04
  shell: bash
  ports:
  - 9090
  - 8080
  environment:
    DEMO_MODE: firehose
    ELASTIC_DATASET: metrics-demo
    PROXY_ES_KEY_BROKER: http://es3-api:8081
    USE_LOCAL_ELASTIC: "false"
  memory: 2048
virtualmachines:
- name: es3-api
  image: elastic/es3-api-v2
  shell: /bin/bash
  environment:
    OPTIMIZED_FOR: vector
    PRODUCT_TIER: complete
    PROJECT_TYPE: observability
    REGIONS: aws-us-east-1
  memory: 4096
  cpus: 1
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: LLM_PROXY_PROD
- name: ESS_CLOUD_API_KEY
